<div id="scaffold">
    <?php View::content()?>
    <!-- .page -->

    <!-- /floating action -->
 
    <div class="d-md-flex align-items-md-start">
        <h1 class="page-title mr-sm-auto">
            <?php echo $controller_name?>
            <?php //echo var_dump($data) ?>
            <?php //echo var_dump($bigdata) ?>
            <?php //cho var_dump($s) ?>

        </h1>

        <div class="btn-toolbar">
            <a href="/<?php echo NOMBRE_CAJA ?>/default/public/<?php echo $controller_name ?>/crear " type="button"
                class="btn btn-light">
                <i class="oi oi-plus"></i>
                <span class="ml-1">Nuevo Elemento</span>
            </a>

            <a href="/<?php echo NOMBRE_CAJA ?>/default/public/<?php echo $controller_name ?>/filtrar " type="button"
                class="btn btn-light">
                <i class="oi oi-zoom-in"></i>
                <span class="ml-1">Filtrar Elementos</span>
            </a>

            <a href="/<?php echo NOMBRE_CAJA ?>/default/public/<?php echo $controller_name ?>/masterdetail/1 "
                type="button" class="btn btn-light">
                <i class="oi oi-loop-square"></i>
                <span class="ml-1">Maestro-Detalle</span>
            </a>

            <a href="/<?php echo NOMBRE_CAJA ?>/default/public/<?php echo $controller_name ?> " type="button"
                class="btn btn-light">
                <i class="oi oi-list-rich"></i>
                <span class="ml-1">Listar Elementos</span>
            </a>
        </div>
        <!--<form >
        <input type="text" name="busqueda" id="busqueda" placeholder="Buscar">
        <input type="submit" value="Buscar" class="btn-search">
        </div>-->

        <!-- .btn-toolbar -->

        <!-- /.btn-toolbar -->
    </div>

    <!--
    <a class="btn btn-danger btn-block" href="/florencioK/default/public/<?php echo $controller_name ?>/crear">
    Nuevo
    -->
    </a>
</div>


<?php View::partial('sicap_form_builder/index', false, 
array('bigdata' => $bigdata , 'data'=>$data,
    'primaryKey'=>$primaryKey, 
    'configuraciondata'=>$configuraciondata, 
    'objeto'=> $objeto,
    )) ?>