<div id="scaffold">
    <?php View::content()?>
    <!-- .page -->

    <!-- /floating action -->

    <div class="d-md-flex align-items-md-start">
        <h1 class="page-title mr-sm-auto">
            <?php echo( $controller_name . ' - ' . $tablaEsclavo)?>
        </h1>



        <div class="btn-toolbar">
            <a href="/<?php echo NOMBRE_CAJA ?>/default/public/<?php echo $controller_name ?>/crear " type="button"
                class="btn btn-light">
                <i class="oi oi-plus"></i>
                <span class="ml-1">Nuevo Elemento</span>
            </a>

            <a href="/<?php echo NOMBRE_CAJA ?>/default/public/<?php echo $controller_name ?>/filtrar " type="button"
                class="btn btn-light">
                <i class="oi oi-zoom-in"></i>
                <span class="ml-1">Filtrar Elementos</span>
            </a>

            <a href="/<?php echo NOMBRE_CAJA ?>/default/public/<?php echo $controller_name ?>/masterdetail/1 "
                type="button" class="btn btn-light">
                <i class="oi oi-loop-square"></i>
                <span class="ml-1">Maestro-Detalle</span>
            </a>

            <a href="/<?php echo NOMBRE_CAJA ?>/default/public/<?php echo $controller_name ?> " type="button"
                class="btn btn-light">
                <i class="oi oi-list-rich"></i>
                <span class="ml-1">Listar Elementos</span>
            </a>
        </div>
        <!--<form >
        <input type="text" name="busqueda" id="busqueda" placeholder="Buscar">
        <input type="submit" value="Buscar" class="btn-search">
        </div>-->

        <!-- .btn-toolbar -->

        <!-- /.btn-toolbar -->
    </div>

    <!--
    <a class="btn btn-danger btn-block" href="/florencioK/default/public/<?php echo $controller_name ?>/crear">
    Nuevo
    -->
    </a>
</div>

<div id='contonedor'>

    <?php if (isset($data->items) && (count($data->items) > 0)) : ?>
    <div class="page-section">
        <?php foreach ($data->items as $key => $item) : ?>
        <?php $pk =  $item->primary_key[0]  ?>

        <div id="accordion" class="card-expansion">
            <div class="card card-expansion-item expanded">
                <div class="card-header border-0 pb-0" id="heading<?php echo $key ?>">

                    <h1 class="section-title  p-0">
                        <?= ucfirst( $controller_name) ?> (Maestro)
                    </h1>
                    <table class=" table table-striped dt-responsive  table-bordered w-100 text-center">
                        <thead class="thead-dark">
                            <tr>
                                <?php foreach ($dataTablaConf as $titulo) :?>
                                <?php if ($titulo->VisibleEnTabla) :?>
                                <th> <?= h($titulo->Label) ?> </th>
                                <?php endif ?>
                                <?php endforeach ?>
                                <th>Acciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <?php foreach ($dataTablaConf as $titulo) :?>

                                <?php if ($titulo->VisibleEnTabla) : ?>

                                <?php $nombreCampo = $titulo->Name ?>
                                <?php $campoCambio = $titulo->CampoForaneoValor ?>
                                <?php if (strlen($titulo->Sentencias) > 0) :?>
                                <?php $s = $item->$nombreCampo?>
                                <?php $sql = "SELECT $titulo->CampoForaneoValor FROM $titulo->TablaForanea WHERE $titulo->Name LIKE $s" ?>
                                <?php   $valorForaneo = (new $titulo->TablaForanea)->find_by_sql($sql) ?>
                                <td><?= h($valorForaneo->$campoCambio) ?> </td>
                                <?php else:?>
                                <td> <?= h($item->$nombreCampo) ?></td>
                                <?php endif?>

                                <?php endif ?>
                                <?php endforeach ?>

                                <td>
                                    <?= Html::linkAction("ver/".$item->$pk, '<button class="btn btn-sm btn-icon btn-secondary"><i class="fa fa-eye"></i></button>') ?>
                                    <?= Html::linkAction("editar/".$item->$pk, '<button class="btn btn-sm btn-icon btn-secondary"><i class="fa fa-pencil-alt"></i></button>') ?>
                                    <?= Html::linkAction("borrar/".$item->$pk, '<button class="btn btn-sm btn-icon btn-secondary"><i class="far fa-trash-alt"></i></button>', 'onclick="return confirm(\'¿Está seguro?\')"') ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <button class="btn btn-reset" data-toggle="collapse" data-target="#collapse<?php echo $key ?>"
                        aria-expanded="true" aria-controls="collapse<?php echo $key ?>">
                        <span class="collapse-indicator mr-2">
                            <i class="fa fa-fw fa-caret-right"></i>
                        </span>
                        Desplegar <?= ucfirst( $tablaEsclavo ) ?>
                    </button>
                    <hr>
                </div>


                <div id="collapse<?php echo $key ?>" class="collapse" aria-labelledby="heading<?php echo $key ?>"
                    data-parent="#accordion">
                    <div class="card-body pt-0">
                        <?php $pkMaestro = $dataTablaConf[0]->MaestroCampoId ?>
                        <?php $pkEsclavo = $dataTablaConf[0]->EsclavoCampoId ?>

                        <?php $esclavosXmaestro = (new $tablaEsclavo)->find("$pkMaestro LIKE ".$item->$pkEsclavo); ?>

                        <?php View::partial('sicap_form_builder/index', false, 
                            array('bigdata' => null , 'data'=>$esclavosXmaestro,
                                'primaryKey'=>$campoConf->primary_key[0], 
                                'configuraciondata'=>$dataEsclavo, 
                                'objeto'=> null,
                                'linkAction'=>$tablaEsclavo
                        )) ?>


                    </div>
                </div>
            </div>
        </div>

        <?php endforeach ?>
        <?php else : // Si no hay items?>
        <h2>No hay ningún registro</h2>
        <?php endif ?>
    </div>
</div>