<aside class="app-aside app-aside-expand-md app-aside-light">
    <!-- .aside-content -->
    <div class="aside-content">
        <!-- .aside-header -->
        <header class="aside-header d-block d-md-none">
            <!-- .btn-account -->
            <button class="btn-account" type="button" data-toggle="collapse" data-target="#dropdown-aside">
                <span class="user-avatar user-avatar-lg">
                    <img src="assets/images/avatars/profile.jpg" alt="">
                </span>
                <span class="account-icon">
                    <span class="fa fa-caret-down fa-lg"></span>
                </span>
                <span class="account-summary">
                    <span class="account-name">Beni Arisandi</span>
                    <span class="account-description">Marketing Manager</span>
                </span>
            </button>
            <!-- /.btn-account -->
            <!-- .dropdown-aside -->
            <div id="dropdown-aside" class="dropdown-aside collapse">
                <!-- dropdown-items -->
                <div class="pb-3">
                    <a class="dropdown-item" href="user-profile.html"><span class="dropdown-icon oi oi-person"></span>
                        Profile</a>
                    <a class="dropdown-item" href="auth-signin-v1.html"><span
                            class="dropdown-icon oi oi-account-logout"></span> Logoutkkk</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Help Center</a>
                    <a class="dropdown-item" href="#">Ask Forum</a>
                    <a class="dropdown-item" href="#">Keyboard Shortcuts</a>
                </div>
                <!-- /dropdown-items -->
            </div>
            <!-- /.dropdown-aside -->
        </header>
        <!-- /.aside-header -->
        <br>

        <!-- .aside-menu -->
        <div class="aside-menu overflow">
            <!-- .stacked-menu -->
            <nav id="stacked-menu" class="stacked-menu">
                <!-- .menu -->
                <ul class="menu">

                    <?php //$menu = (new menucompleto)->find( 'conditions: INSTR(Nombre, "WflsTest") > 0 '); ?>

                    <?php $menu = (new mymenugenerador)->buscarPorIdPadre() ?>





                    <?php foreach ($menu  as $key => $value): ?>

                    <?php if(true): // if($value->parent_id == 0 && Auth::get('Grupo') == 'ADMINISTRADOR'): ?>
                    <?php View::partial('snippets/aside/level-menu', false, array('menupadre' => $value)) ?>

                    <?php endif ?>

                    <?php endforeach ?>

                </ul>
                <!-- /.menu -->
            </nav>
            <!-- /.stacked-menu -->
        </div>
        <!-- /.aside-menu -->

        <!-- Skin changer -->
        <footer class="aside-footer border-top p-2">
            <button class="btn btn-light btn-block text-primary" data-toggle="skin">
                <span class="d-compact-menu-none">Modo Nocturno</span>
                <i class="fas fa-moon ml-1"></i>
            </button>
        </footer>
        <!-- /Skin changer -->
    </div>
    <!-- /.aside-content -->
</aside>