<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- End Required meta tags -->


    <?php View::partial('head') ?>
 
  </head>

  <body>
    <!-- .app -->
    <div class="app">
      <!--[if lt IE 10]>
      <div class="page-message" role="alert">You are using an <strong>outdated</strong> browser. Please <a class="alert-link" href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</div>
      <![endif]-->

      <!-- .app-header 
      {% include header-nosearch.html %}-->
      <?php View::partial('header-nosearch') ?>

      <!-- /.app-header -->

      <!-- .app-aside 
      {% include aside.html %}
      /.app-aside -->
      <?php View::partial('aside') ?>

      <!-- .app-main -->
      <main class="app-main">
        <!-- .wrapper -->
        <div class="wrapper">
       <!--   {{content}} -->
        <?php View::content() ?>
        </div>
        <!-- /.wrapper --

        {% include footer.html %}<-->
        <?php View::partial('foorter') ?>

      </main>
      <!-- /.app-main -->
    </div>
    <!-- /.app --
    {% include scripts.html %} -->

    <?php View::partial('scripts') ?>


  </body>
</html>
