<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <?php View::partial('head') ?>

</head>


<body data-spy="scroll" data-target="#nav-content" data-offset="76">

    <body>
        <div class="app">


            <?php View::partial('header') ?>

            <?php View::partial('aside', '', array('data'=> $data)) ?>

            <main class="app-main">
                <div class="wrapper">
                    <?php View::content() ?>
                </div>


            </main>
        </div>

        <?php View::partial('scripts') ?>


    </body>

</html>