<header class="app-header app-header-dark">
    <!-- .top-bar -->
    <div class="top-bar">
        <!-- .top-bar-brand -->
        <div class="top-bar-brand">
            <!-- toggle aside menu -->
            <button class="hamburger hamburger-squeeze mr-2" type="button" data-toggle="aside-menu"
                aria-label="toggle aside menu">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
            <!-- /toggle aside menu -->
            <a href="index.html">
                <?= Html::img('sicap-logo.png', '', 'style="max-width: 150px;" class="img-fluid max-auto "') ?>
            </a>
        </div>
        <!-- /.top-bar-brand -->

        <!-- .top-bar-list -->
        <div class="top-bar-list">
            <!-- .top-bar-item -->
            <div class="top-bar-item px-2 d-md-none d-lg-none d-xl-none">
                <!-- toggle menu -->
                <button class="hamburger hamburger-squeeze" type="button" data-toggle="aside" aria-label="toggle menu">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
                <!-- /toggle menu -->
            </div>
            <!-- /.top-bar-item -->

            <!-- .top-bar-item -->
            <div class="top-bar-item top-bar-item-full">
                <!--
                hide search bar
                <form class="top-bar-search">
                    <div class="input-group input-group-search dropdown">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span class="oi oi-magnifying-glass"></span>
                            </span>
                        </div>
                        <input type="text" class="form-control" data-toggle="dropdown" aria-label="Search"
                            placeholder="Search">
                        <div class="dropdown-menu dropdown-menu-rich dropdown-menu-xl ml-n4 mw-100">
                            <div class="dropdown-arrow ml-3"></div>
                            <div class="dropdown-scroll perfect-scrollbar h-auto" style="max-height: 360px">
                                <div class="list-group list-group-flush list-group-reflow mb-2">
                                    <h6 class="list-group-header d-flex justify-content-between">
                                        <span>Shortcut</span>
                                    </h6>
                                    <div class="list-group-item py-2">
                                        <a href="#" class="stretched-link"></a>
                                        <div class="tile tile-sm bg-muted">
                                            <i class="fas fa-user-plus"></i>
                                        </div>
                                        <div class="ml-2">Create user</div>
                                    </div>

                                    <div class="list-group-item py-2">
                                        <a href="#" class="stretched-link"></a>
                                        <div class="tile tile-sm bg-muted">
                                            <i class="fas fa-dollar-sign"></i>
                                        </div>
                                        <div class="ml-2">Create invoice</div>
                                    </div>
                                    <h6 class="list-group-header d-flex justify-content-between mt-2">
                                        <span>In projects</span>
                                        <a href="#" class="font-weight-normal">Show more</a>
                                    </h6>
                                    <div class="list-group-item py-2">
                                        <a href="#" class="stretched-link">
                                            <span class="sr-only">Go to search result</span>
                                        </a>
                                        <div class="user-avatar user-avatar-sm bg-muted">
                                            < //Html::img("../assets/images/avatars/bootstrap.svg") ?>
                                        </div>
                                        <div class="ml-2">
                                            <div class="mb-n1">Bootstrap</div>
                                            <small class="text-muted">Just now</small>
                                        </div>
                                    </div>
                                    <div class="list-group-item py-2">
                                        <a href="#" class="stretched-link">
                                            <span class="sr-only">Go to search result</span>
                                        </a>
                                        <div class="user-avatar user-avatar-sm bg-muted">
                                            < //Html::img("../assets/images/avatars/slack.svg") ?>
                                        </div>
                                        <div class="ml-2">
                                            <div class="mb-n1">Slack</div>
                                            <small class="text-muted">Updated 25 minutes ago</small>
                                        </div>
                                    </div>
                                    <h6 class="list-group-header d-flex justify-content-between mt-2">
                                        <span>Another section</span>
                                        <a href="#" class="font-weight-normal">Show more</a>
                                    </h6>
                                    <div class="list-group-item py-2">
                                        <a href="#" class="stretched-link">
                                            <span class="sr-only">Go to search result</span>
                                        </a>
                                        <div class="tile tile-sm bg-muted">P</div>
                                        <div class="ml-2">
                                            <div class="mb-n1">Product name</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="#" class="dropdown-footer">Show all results</a>
                        </div>
                      </div>
                    </form>
                  -->
            </div>

            <div class="top-bar-item top-bar-item-right px-0 d-none d-sm-flex">

                <!-- remove messages and notifications
                <ul class="header-nav nav">
                    <li class="nav-item dropdown header-nav-dropdown has-notified">
                        <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="oi oi-pulse"></span>
                        </a>
                        <?php //View::partial('ui/dropdown-notifications')?>
                    </li>
                    <li class="nav-item dropdown header-nav-dropdown has-notified">
                        <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="oi oi-envelope-open"></span>
                        </a>
                        <?php //View::partial('ui/dropdown-messages')?>
                    </li>

                    <li class="nav-item dropdown header-nav-dropdown">
                        <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="oi oi-grid-three-up"></span>
                        </a>
                        <?php //View::partial('ui/dropdown-sheets')?>

                    </li>
                </ul>
-->

                <!-- .btn-account -->
                <div class="dropdown d-none d-md-flex">
                    <button class="btn-account" type="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <span class="user-avatar user-avatar-md">
                            <img src="<?= (new usuarios)->getImage(Auth::get('IdUsuario'), 'usuarios')?>" alt="" srcset="">
                        </span>
                        <span class="account-summary pr-lg-4 d-none d-lg-block">
                            <span class="account-name">
                                <?php echo '[ '. ucfirst(Auth::get('Usuario')).' ]' ?>
                            </span>
                            <span class="account-description">
                                <?php if (class_exists('gruporoles')): ?>
                                <?php echo '[ '. (new gruporoles)->find(Auth::get('grupos_id'))->rol .' ]' ?>
                                <?php endif ?>
                            </span>

                            <span class="account-description">
                                <?php echo '[ '.  Auth::get('Grupo') .' ]' ?>

                            </span>
                        </span>
                    </button>
                    <!-- .dropdown-menu -->
                    <div class="dropdown-menu">
                        <div class="dropdown-arrow d-lg-none" x-arrow></div>
                        <div class="dropdown-arrow ml-3 d-none d-lg-block"></div>
                        <h6 class="dropdown-header d-none d-md-block d-lg-none">Beni Arisandi</h6>
                        <a class="dropdown-item"
                            href="/<?= NOMBRE_CAJA ?>/default/public/usuarios/perfil/<?= Auth::get('IdUsuario')?>"><span
                                class="dropdown-icon oi oi-person"></span> Perfil</a>
                        <a class="dropdown-item" href="/<?= NOMBRE_CAJA ?>/default/public/login/logout">
                            <span class="dropdown-icon oi oi-account-logout"></span> Salir </a>
                        <div class="dropdown-divider"></div>
                        <!--
                        <a class="dropdown-item" href="#">Help Center</a>
                        <a class="dropdown-item" href="#">Ask Forum</a>
                        <a class="dropdown-item" href="#">Keyboard Shortcuts</a>
                        -->
                    </div>
                    <!-- /.dropdown-menu -->
                </div>
                <!-- /.btn-account -->
            </div>
            <!-- /.top-bar-item -->
        </div>
        <!-- /.top-bar-list -->
    </div>
    <!-- /.top-bar -->
</header>
