<header class="app-header app-header-dark">
  <!-- .top-bar -->
  <div class="top-bar">
    <!-- .top-bar-brand -->
    <div class="top-bar-brand">
      <!-- toggle aside menu -->
      <button class="hamburger hamburger-squeeze mr-2" type="button" data-toggle="aside-menu" aria-label="toggle aside menu">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </button>
      <!-- /toggle aside menu -->
      <a href="index.html">
            <?= Html::img('sicap-logo.png', '', 'style="max-width: 150px;" class="img-fluid max-auto "') ?>
      </a>
    </div>
    <!-- /.top-bar-brand -->

    <!-- .top-bar-list -->
    <div class="top-bar-list">
      <!-- .top-bar-item -->
      <div class="top-bar-item px-2 d-md-none d-lg-none d-xl-none">
        <!-- toggle menu -->
        <button class="hamburger hamburger-squeeze" type="button" data-toggle="aside" aria-label="toggle menu">
          <span class="hamburger-box">
            <span class="hamburger-inner"></span>
          </span>
        </button>
        <!-- /toggle menu -->
      </div>
      <!-- /.top-bar-item -->

      <!-- .top-bar-item -->
      <div class="top-bar-item top-bar-item-full">
        <!-- .top-bar-search -->
        <form class="top-bar-search">
          <!-- .input-group -->
          <div class="input-group input-group-search dropdown">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <span class="oi oi-magnifying-glass"></span>
              </span>
            </div>
            <input type="text" class="form-control" data-toggle="dropdown" aria-label="Search" placeholder="Search">
            <!-- .dropdown-menu -->
            <div class="dropdown-menu dropdown-menu-rich dropdown-menu-xl ml-n4 mw-100">
              <div class="dropdown-arrow ml-3"></div>
              <!-- .dropdown-scroll -->
              <div class="dropdown-scroll perfect-scrollbar h-auto" style="max-height: 360px">
                <!-- .list-group -->
                <div class="list-group list-group-flush list-group-reflow mb-2">
                  <h6 class="list-group-header d-flex justify-content-between">
                    <span>Shortcut</span>
                  </h6>
                  <!-- .list-group-item -->
                  <div class="list-group-item py-2">
                    <a href="#" class="stretched-link"></a>
                    <div class="tile tile-sm bg-muted">
                      <i class="fas fa-user-plus"></i>
                    </div>
                    <div class="ml-2">Create user</div>
                  </div>
                  <!-- /.list-group-item -->
                  <!-- .list-group-item -->
                  <div class="list-group-item py-2">
                    <a href="#" class="stretched-link"></a>
                    <div class="tile tile-sm bg-muted">
                      <i class="fas fa-dollar-sign"></i>
                    </div>
                    <div class="ml-2">Create invoice</div>
                  </div>
                  <!-- /.list-group-item -->
                  <h6 class="list-group-header d-flex justify-content-between mt-2">
                    <span>In projects</span>
                    <a href="#" class="font-weight-normal">Show more</a>
                  </h6>
                  <!-- .list-group-item -->
                  <div class="list-group-item py-2">
                    <a href="#" class="stretched-link">
                      <span class="sr-only">Go to search result</span>
                    </a>
                    <div class="user-avatar user-avatar-sm bg-muted">
                      <?= Html::img( "../assets/images/avatars/bootstrap.svg" ) ?>
                    </div>
                    <div class="ml-2">
                      <div class="mb-n1">Bootstrap</div>
                      <small class="text-muted">Just now</small>
                    </div>
                  </div>
                  <!-- /.list-group-item -->
                  <!-- .list-group-item -->
                  <div class="list-group-item py-2">
                    <a href="#" class="stretched-link">
                      <span class="sr-only">Go to search result</span>
                    </a>
                    <div class="user-avatar user-avatar-sm bg-muted">
                      <?= Html::img( "../assets/images/avatars/slack.svg" ) ?>
                    </div>
                    <div class="ml-2">
                      <div class="mb-n1">Slack</div>
                      <small class="text-muted">Updated 25 minutes ago</small>
                    </div>
                  </div>
                  <!-- /.list-group-item -->
                  <!-- /.list-group-item -->
                  <h6 class="list-group-header d-flex justify-content-between mt-2">
                    <span>Another section</span>
                    <a href="#" class="font-weight-normal">Show more</a>
                  </h6>
                  <!-- .list-group-item -->
                  <div class="list-group-item py-2">
                    <a href="#" class="stretched-link">
                      <span class="sr-only">Go to search result</span>
                    </a>
                    <div class="tile tile-sm bg-muted">P</div>
                    <div class="ml-2">
                      <div class="mb-n1">Product name</div>
                    </div>
                  </div>
                  <!-- /.list-group-item -->
                </div>
                <!-- /.list-group -->
              </div>
              <!-- /.dropdown-scroll -->
              <a href="#" class="dropdown-footer">Show all results</a>
            </div>
            <!-- /.dropdown-menu -->
          </div>
          <!-- /.input-group -->
        </form>
        <!-- /.top-bar-search -->
      </div>
      <!-- /.top-bar-item -->
 
      <!-- .top-bar-item -->
      <div class="top-bar-item top-bar-item-right px-0 d-none d-sm-flex">
        <!-- .nav -->
        <ul class="header-nav nav">
          <!-- .nav-item -->
          <li class="nav-item dropdown header-nav-dropdown has-notified">
            <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="oi oi-pulse"></span>
            </a>
            <?php View::partial('ui/dropdown-notifications') ?>
           <!-- {% include ui/dropdown-notifications.html %} -->
          </li>
          <!-- /.nav-item -->
          <!-- .nav-item -->
          <li class="nav-item dropdown header-nav-dropdown has-notified">
            <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="oi oi-envelope-open"></span>
            </a>
            <!--{% include ui/dropdown-messages.html %} ->
            <?php View::partial('ui/dropdown-messages') ?>

          </li>
          <!-- /.nav-item -->
          <!-- .nav-item -->
          <li class="nav-item dropdown header-nav-dropdown">
            <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="oi oi-grid-three-up"></span>
            </a>
           <!-- {% include ui/dropdown-sheets.html %} -->
           <?php View::partial('ui/dropdown-sheets') ?>

          </li>
          <!-- /.nav-item -->
        </ul>
        <!-- /.nav -->
 
        <!-- .btn-account -->
        <div class="dropdown d-none d-md-flex">
          <button class="btn-account" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="user-avatar user-avatar-md">
              <?= Html::img("../assets/images/avatars/profile.jpg") ?>
            </span>
            <span class="account-summary pr-lg-4 d-none d-lg-block">
              <span class="account-name">
                <?php echo '[ '. Auth::get('user') .' ]' ?>
              </span>
              <span class="account-description">
              <?php echo '[ '. (new gruporoles)->find( Auth::get('grupos_id'))->rol .' ]' ?>

              </span>

              <span class="account-description">
              <?php echo '[ '.  Auth::get('puesto') .' ]' ?>

              </span>
            </span>
          </button>
          <!-- .dropdown-menu -->
          <div class="dropdown-menu">
            <div class="dropdown-arrow d-lg-none" x-arrow></div>
            <div class="dropdown-arrow ml-3 d-none d-lg-block"></div>
            <h6 class="dropdown-header d-none d-md-block d-lg-none">Beni Arisandi</h6>
            <a class="dropdown-item" href="user-profile.html"><span class="dropdown-icon oi oi-person"></span> Profile</a>
            <a class="dropdown-item" <?php echo ' href="/florencioK/default/public/login/logout" ' ?></a> <span class="dropdown-icon oi oi-account-logout"></span> Logout</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Help Center</a>
            <a class="dropdown-item" href="#">Ask Forum</a>
            <a class="dropdown-item" href="#">Keyboard Shortcuts</a>
          </div>
          <!-- /.dropdown-menu -->
        </div>
        <!-- /.btn-account -->
      </div>
      <!-- /.top-bar-item -->
    </div>
    <!-- /.top-bar-list -->
  </div>
  <!-- /.top-bar -->
</header>
