<aside class="app-aside app-aside-expand-md app-aside-light">
    <!-- .aside-content -->
    <div class="aside-content">
        <!-- .aside-header -->
        <header class="aside-header d-block d-md-none">
            <!-- .btn-account -->
            <button class="btn-account" type="button" data-toggle="collapse" data-target="#dropdown-aside">
                <span class="user-avatar user-avatar-lg">
                    <img src="assets/images/avatars/profile.jpg" alt="">
                </span>
                <span class="account-icon">
                    <span class="fa fa-caret-down fa-lg"></span>
                </span>
                <span class="account-summary">
                    <span class="account-name">Beni Arisandi</span>
                    <span class="account-description">Marketing Manager</span>
                </span>
            </button>
            <!-- /.btn-account -->
            <!-- .dropdown-aside -->
            <div id="dropdown-aside" class="dropdown-aside collapse">
                <!-- dropdown-items -->
                <div class="pb-3">
                    <a class="dropdown-item" href="user-profile.html"><span class="dropdown-icon oi oi-person"></span>
                        Profile</a>
                    <a class="dropdown-item" href="auth-signin-v1.html"><span
                            class="dropdown-icon oi oi-account-logout"></span> Logout</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Help Center</a>
                    <a class="dropdown-item" href="#">Ask Forum</a>
                    <a class="dropdown-item" href="#">Keyboard Shortcuts</a>
                </div>
                <!-- /dropdown-items -->
            </div>
            <!-- /.dropdown-aside -->
        </header>
        <!-- /.aside-header -->
        <!-- .aside-menu -->
        <div class="aside-menu overflow-hidden">
            <!-- .stacked-menu -->
            <nav id="stacked-menu" class="stacked-menu">
                <!-- .menu -->
                <ul class="menu">
                    <?php /*

          $_data = (new Menus)->find("status ORDER BY position ASC ");
          //echo $_data[0]->Text;
          //$ad = get_object_vars($_data[0]);
          //echo $_data[2]["text"];
          //echo $ad["text"];
          //var_dump($ad);
          foreach ($_data as $index => $row) {
            // verificar si la fila tiene el mismo grupo que el usuario actual (es informacion accesible)
            if(  $row->grupo_usuarios == (new grupos)->find( Auth::get('grupos_id') )->nivel  ){
            //$row = get_object_vars($_data[$key]);
           if($row->parent==0){
            if($row->type== 'header')
              View::partial('snippets/aside/header-menu', false, array('levelMenu' => $row));
            if($row->type== 'link')
              View::partial('snippets/aside/level-menu', false, array('levelMenu' => $row));
           }
          }
        }

          /*
          $_data =file_get_contents("json/aside-menu.json");
          $json = json_decode($_data, true);

          foreach ($json["aside-menu"] as $key => $value) {
             if($value["type"]== 'header')
               View::partial('snippets/aside/header-menu', false, array('levelMenu' => $value));
             if($value["type"]== 'link')
               View::partial('snippets/aside/level-menu', false, array('levelMenu' => $value));
          }*/
          ?>
                </ul>
                <!-- /.menu -->
            </nav>
            <!-- /.stacked-menu -->
        </div>
        <!-- /.aside-menu -->

        <!-- Skin changer -->
        <footer class="aside-footer border-top p-2">
            <button class="btn btn-light btn-block text-primary" data-toggle="skin">
                <span class="d-compact-menu-none">Night mode</span>
                <i class="fas fa-moon ml-1"></i>
            </button>
        </footer>
        <!-- /Skin changer -->
    </div>
    <!-- /.aside-content -->
</aside>