<main class="auth">
    <header id="auth-header" class="auth-header" style="background-color: #852A6D;">
        <h1>
            <a href="index.html">
                <?= Html::img('sicap-logo.png', '', 'style="max-width: 500px;" class="img-fluid max-auto "') ?>
            </a>
            <span class="sr-only">Sign In</span>
        </h1>
        <p> ¿Aun no activas tu cuenta? <?= Html::link('login/activar', 'Activar') ?>
        </p>
    </header>

    <?= View::content() ?>



    <?= Form::open('login', 'post', "class='auth-form'")?>

    <div class="form-group">
        <div class="form-label-group">
            <?= Form::text('usr', ' id="inputUser" class="form-control" placeholder="Username" autofocus="" ') ?>
            <label for="inputUser">Usuario</label>
        </div>
    </div>
    <div class="form-group">
        <div class="form-label-group">
            <?= Form::password('pwd', ' id="inputPassword" class="form-control" placeholder="Password" ') ?>
            <label for="inputPassword">Clave</label>
        </div>
    </div>
    <div class="form-group">
        <?= Form::submit('Entrar', 'class="btn btn-lg btn-primary btn-block"') ?>

    </div>


    <?= Form::close() ?>

    <footer class="auth-footer">
        © 2021 Todos los derechos reservados. <a href="#">Acuerdo </a> y <a href="#">Teminos</a>
    </footer>
</main>

<!--
<div class="form-group text-center">
    <div class="custom-control custom-control-inline custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="remember-me"> <label class="custom-control-label"
            for="remember-me">Keep me sign in(aun no funciona)</label>
    </div>
</div>
<div class="text-center pt-3">
    <a href="auth-recovery-username.html" class="link">¿Olvidaste tu contraseña (aun no funciona)?</a>
</div>
-->