<div id='contonedor'>

    <div class="form-group row">
        <!-- .input-group -->
        <div class="input-group input-group-alt col-11">
            <!-- .input-group-prepend -->
            <div class="input-group-prepend ">
                <select class="custom-select ">
                    <option selected>Buscar Por</option>
                    <option value="tipo">Tipo</option>
                    <option value="fecha">Fecha</option>
                    <option value="bene">Beneficiario</option>
                    <option value="elab">Elaboro</option>
                    <option value="aplic">Aplicion</option>
                    <option value="fuente">Fuente</option>
                    <option value="monto">Monto</option>
                </select>
            </div>detallepolizasdetallepolizas
            <!-- /.input-group-prepend -->
            <!-- .input-group -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><span class="oi oi-magnifying-glass"></span></span>
                </div>
                <input type="text" class="form-control" placeholder="Buscar">
            </div>
            <!-- /.input-group -->
        </div>

        <div class="col-1">
            <button type="button" class="btn btn-block btn-primary" btn-lg btn-block">
                <i class="oi oi-magnifying-glass" aria-hidden="true"></i>

                Buscar
            </button>
        </div>
    </div>

    <?php if (isset($data->items) && (count($data->items) > 0)) : ?>
    <div class="page-section">
        <?php foreach ($data->items as $key => $item) : ?>
        <?php $pk =  $item->primary_key[0]  ?>

        <div id="accordion" class="card-expansion">
            <div class="card card-expansion-item expanded">
                <div class="card-header border-0"
                    id="heading<?php echo $key ?>">
                    <button class="btn btn-reset" data-toggle="collapse"
                        data-target="#collapse<?php echo $key ?>"
                        aria-expanded="true"
                        aria-controls="collapse<?php echo $key ?>">
                        <span class="collapse-indicator mr-2">
                            <i class="fa fa-fw fa-caret-right"></i>
                        </span>
                        <span> <?php echo "$model ". $key + 1 ?></span>
                    </button>



                    <a href="/KumbiaSoft/polizas/poliza/<?php echo $pk?>"
                        target="_blank" type="button" class="btn btn-icon btn-light">
                        <i class="fa fa-copy"></i>
                    </a>
                    <a type="button" class="btn btn-icon btn-light">
                        <i class="fa fa-download"></i>
                    </a>



                    <table class="dtTablePrin table table-bordered dt-responsive  w-100">
                        <thead class="thead-dark">
                            <?//echo var_dump($ctd) ?>
                            <tr>
                                <?php foreach ($ctd as $titulo) :?>
                                <?php if ($titulo->VisibleEnTabla) :?>
                                <th> <?= h($titulo->Label) ?>
                                </th>
                                <?php endif ?>
                                <?php endforeach ?>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <?php foreach ($ctd as $titulo) :?>

                                <?php if ($titulo->VisibleEnTabla) : ?>

                                <?php $nombreCampo = $titulo->Name ?>
                                <?php $campoCambio = $titulo->CampoForaneoValor ?>
                                <?php if (strlen($titulo->Sentencias) > 0) :?>
                                <?php $s = $item->$nombreCampo?>
                                <?php $sql = "SELECT $titulo->CampoForaneoValor FROM $titulo->TablaForanea WHERE $titulo->Name LIKE $s" ?>
                                <?php   $valorForaneo = (new $titulo->TablaForanea)->find_by_sql($sql) ?>
                                <td><?= h($valorForaneo->$campoCambio) ?>
                                </td>
                                <?php else:?>
                                <td> <?= h($item->$nombreCampo) ?></td>
                                <?php endif?>

                                <?php endif ?>
                                <?php endforeach ?>

                                <td style="width:100px; min-width:100px;">
                                    <?= Html::linkAction("ver/".$item->$pk, '<button class="btn btn-sm btn-icon btn-secondary"><i class="fa fa-eye"></i></button>') ?>
                                    <?= Html::linkAction("editar/".$item->$pk, '<button class="btn btn-sm btn-icon btn-secondary"><i class="fa fa-pencil-alt"></i></button>') ?>
                                    <?= Html::linkAction("borrar/".$item->$pk, '<button class="btn btn-sm btn-icon btn-secondary"><i class="far fa-trash-alt"></i></button>', 'onclick="return confirm(\'¿Está seguro?\')"') ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>


                </div>

                <hr>

                <div id="collapse<?php echo $key ?>" class="collapse"
                    aria-labelledby="heading<?php echo $key ?>"
                    data-parent="#accordion">
                    <div class="card-body ">
                        <?php $pkMaestro = $ctd[0]->MaestroCampoId ?>
                        <?php $pkEsclavo = $ctd[0]->EsclavoCampoId ?>

                        <?php $esclavosXmaestro = (new $tablaesclavo)->find("$pkMaestro LIKE ".$item->$pkEsclavo); ?>

                        <table id="" class="dtTableSec  table  table-bordered dt-responsive  w-100">
                            <thead class=" thead-light">
                                <tr>
                                    <th>#</th>
                                    <?php foreach ($dataEsclavo as $campoConf): ?>
                                    <?php if ($campoConf->VisibleEnTabla): ?>
                                    <th> <?= h($campoConf->Label) ?>
                                    </th>
                                    <?php endif ?>
                                    <?php endforeach ?>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($esclavosXmaestro as $key => $val) : ?>
                                <tr>
                                    <?php $pks = $val->primary_key[0] ?>
                                    <td> <?= h($key+1) ?>
                                    </td>

                                    <?php foreach ($dataEsclavo as $campoConf): ?>
                                    <?php if ($campoConf->VisibleEnTabla): ?>
                                    <?php $nombreCampo = $campoConf->Name ?>
                                    <?php $campoCambio = $campoConf->CampoForaneoValor ?>
                                    <?php if (strlen($campoConf->Sentencias) > 0) :?>
                                    <?php $s = $val->$nombreCampo?>
                                    <?php $sql = "SELECT $campoConf->CampoForaneoValor FROM $campoConf->TablaForanea WHERE $campoConf->Name LIKE $s" ?>
                                    <?php   $valorForaneo = (new $campoConf->TablaForanea)->find_by_sql($sql) ?>
                                    <td><?= h($valorForaneo->$campoCambio) ?>
                                    </td>
                                    <?php else:?>
                                    <td> <?= h($val->$nombreCampo) ?>
                                    </td>
                                    <?php endif?>
                                    <?php endif ?>
                                    <?php endforeach ?>

                                    <td>
                                        <?= Html::link("$tablaesclavo/ver/". $val->$pks, '<button class="btn btn-sm btn-icon btn-secondary"><i class="fa fa-eye"></i></button>') ?>
                                        <?= Html::link("$tablaesclavo/editar/". $val->$pks, '<button class="btn btn-sm btn-icon btn-secondary"><i class="fa fa-pencil-alt"></i></button>') ?>
                                        <?= Html::link("$tablaesclavo/borrar/". $val->$pks, '<button class="btn btn-sm btn-icon btn-secondary"><i class="far fa-trash-alt"></i></button>', 'onclick="return confirm(\'¿Está seguro?\')"') ?>

                                    </td>
                                </tr>

                                <?php endforeach ?>
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>

        <?php endforeach ?>
        <?php else : // Si no hay items?>
        <h2>No hay ningún registro</h2>
        <?php endif ?>
    </div>
</div>


