<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php View::partial('head') ?>

</head>

<?php if (false) : ?>

<body data-spy="scroll" data-target="#nav-content" data-offset="76">
    <?php else : ?>

    <body>
        <?php endif ?>
        <div class="app">


            <?php View::partial('header') ?>

            <?php 
            View::partial('aside', '', array( 'menu' => $menu )) ?>


            <main class="app-main">
                <div class="wrapper">

                    <div class="page">
                        <div class="page-inner">
                            <header class="page-title-bar">

                                <div class="page-section">
                                    <div class="card card-fluid">
                                        <div class="card-body">
                                            <?php View::content() ?>


                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
        </div>
        </div>

        <?php //View::partial('footer') ?>
        </main>
        </div>

        <?php View::partial('scripts', null, array( 'action_name' => $action_name) )?>

    </body>

</html>