<!doctype html>
<html lang="en">
  <head>

  <?php View::partial('head') ?>

  </head>

  <body>
    <!--[if lt IE 10]>
    <div class="page-message" role="alert">You are using an <strong>outdated</strong> browser. Please <a class="alert-link" href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</div>
    <![endif]-->

    <?php View::content() ?>


    <?php View::partial('scripts') ?>
  </body>
</html>
