<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags --> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- End Required meta tags -->

    <?php View::partial('head') ?>

  </head>

  <!-- {% if page.hasScrollSpy == true %} -->
  <?php if (false) : ?>
  <body data-spy="scroll" data-target="#nav-content" data-offset="76">
  <?php else : ?>
  <body>
  <?php endif ?>
    <!-- .app --> 
    <div class="app">
      <!--[if lt IE 10]>
      <div class="page-message" role="alert">You are using an <strong>outdated</strong> browser. Please <a class="alert-link" href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</div>
      <![endif]-->

       <!-- .app-header 
      {% include header-nosearch.html %}-->
      <?php View::partial('superheader') ?> 

      <!-- /.app-header -->

      <!-- .app-aside -->
      <?php View::partial('superaside') ?>
     
      <!-- /.app-aside -->

      <!-- .app-main -->
      <main class="app-main">
        <!-- .wrapper -->
        <div class="wrapper text-white">
          <?php View::content() ?>
        </div>

        <?php View::partial('footer') ?>
        <!-- /.wrapper -->
      </main>
      <!-- /.app-main -->
    </div>
    <!-- /.app -->

    <?php View::partial('scripts') ?>

  </body>
</html>
