<div id="scaffold">

    <!-- .page -->
    <div class="page">
        <!-- .page-inner -->
        <div class="page-inner">

            <div class="actions">
                <?= Html::linkAction("crear/", ' <button type="button" class="btn btn-success btn-floated"><span class="fa fa-plus"></span></button>') ?>
            </div>


            <!-- /floating action -->
            <?php View::content() ?>

            <div class="d-md-flex align-items-md-start">
        <h1 class="page-title mr-sm-auto">
            <?php echo $controller_name ?>
        </h1>
        <!-- .btn-toolbar -->
        <div class="btn-toolbar">
          <a href="/KumbiaSoft/default/public/<?php echo $controller_name ?>/pdf/interno" target="_blank" class="btn btn-light">
            <i class="oi oi-data-transfer-download"></i>
            <span class="ml-1">PDF Interno</span>
          </a>
    
          <a href="/KumbiaSoft/default/public/<?php echo $controller_name ?>/pdf"  target="_blank" class="btn btn-light" >
            <i class="oi oi-data-transfer-upload"></i>
            <span class="ml-1">PDF Externo</span>
          </a>
          <div class="dropdown">
            <button type="button" class="btn btn-light" data-toggle="dropdown">
              <span>More</span>
              <span class="fa fa-caret-down"></span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <div class="dropdown-arrow"></div>
              <a href="#" class="dropdown-item">Add tasks</a>
              <a href="#" class="dropdown-item">Invite members</a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">Share</a>
              <a href="#" class="dropdown-item">Archive</a>
              <a href="#" class="dropdown-item">Remove</a>
            </div>
          </div>
        </div>
        <!-- /.btn-toolbar -->
      </div>
            


            <?php if($model == 'polizas') : ?>
                <?php View::partial('index/polizas', false, array('modelo' => $model, 'configTableData'=> $configTableData, 'data' => $data, 'dh'=>$dh ) ) ?>

            <?php elseif($model == 'sucursales'): ?>
                <?php View::partial('index/sucursales', false, array('modelo' => $model, 'configTableData'=>$configTableData, 'data' => $data) ) ?>


            <?php endif ?>
        </div>

        <?php View::partial('paginators/digg', false, array('page' => $data, 'url' => Router::get('controller_path') . '/index')) ?>
    </div>