<div class="page">

    <div class="page-inner">

        <div class="row">

            <div class="col-lg-12">
                <div class="card card-fluid">
                    <div class="card-body">
                        <canvas id="canvas-bar-wfls" class="chartjs"></canvas>
                    </div> 

                    <div class="card-footer">
                    <input type="button"  onclick='bar()'  value="Random" class="btn btn-light btn-block">
                    </div>

                </div>
            </div>
 


            <div class="col-lg-12">
                <div class="card card-fluid">
                    <div class="card-body">
                        <canvas id="canvas-line-wfls" class="chartjs"></canvas>
                    </div>
                    <div class="card-footer">
                            <input type="button"  onclick='line()'  value="Nuevo Dataset" class="btn btn-light btn-block">
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div class="card card-fluid">
                    <div class="card-body">
                        <canvas id="canvas-pie-wfls" class="chartjs"></canvas>
                    </div>
                    <div class="card-footer">
                        <input type="button"  onclick='pie()'  value="Nuevos Datos" class="btn btn-light btn-block">
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div class="card card-fluid">
                    <div class="card-body">
                        <canvas id="canvas-per-wfls" class="chartjs"></canvas>
                    </div>
                    <div class="card-footer">
                        <input type="button"  onclick='per()'  value="Nuevos Datosssss" class="btn btn-light btn-block">
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
