<!-- {% assign actives = page.active | split: "." %} -->
<!-- .menu-item -->


<!-- {% if levelMenu.id == actives[0] %} -->
<?php //if (isset($_SESSION["pageActive"]) && $levelMenu->item==$_SESSION["pageActive"]) : ?>
 
<?php $external_link = str_replace('.php', '', $menupadre->external_link) ?>
<?php $existerelacion = mymenugenerador::esModeloOControlador($external_link) ?>

<li class="menu-item  has-child">

    <?php 
    $link = $external_link;
    if( substr_count($external_link. '/'.NOMBRE_CAJA.'/default/public/') == 0)
        $link =  '/'.NOMBRE_CAJA.'/default/public/'. $link;
    ?>


    <a  class="menu-link">

        <?php if( $menupadre->parent_id == 0) :?>
        <span class="menu-icon fas fa-rocket"></span>
        <?php endif ?>

        <span class="menu-text">

            

            <?= $menupadre->menu_title ?>

        </span>
    </a>

    <?php $actions = $menupadre->buscarPorIdPadre( $menupadre->id ) //['crear', 'index', 'filtrar', 'codificar']// ?>
    <?php View::partial('snippets/aside/menu-item', false, array('padre' => strtolower( $nc ), 'childs' => $actions));?>

</li>
<!-- /.menu-item -->