<!-- {% assign actives = page.active | split: "." %} -->
<!-- child menu -->
<ul class="menu">

    <?php foreach ($childs as $index =>$menuItem) : ?>

    <?php $hijos =$menuItem->buscarPorIdPadre( $menuItem->id ) ?>
    <?php $external_link = str_replace('.php', '', $menuItem->external_link) ?>
    <?php $existerelacion = mymenugenerador::esModeloOControlador($external_link) ?>

    <?php if( $hijos ) : ?>

    <?php View::partial('snippets/aside/level-menu', false, array('menupadre' => $menuItem)) ?>

    <?php else : ?>

    <li class="menu-item">

    <?php 
    $link = $external_link;
    if( substr_count($external_link,  '/'.NOMBRE_CAJA.'/default/public/' ) == 0)
        $link =   '/'.NOMBRE_CAJA.'/default/public/' . $link;
    ?>

        <a href="<?php echo $link ?>" class="menu-link">

            <span class="menu-text">

                <?php if( !$external_link) : ?>
                <?php $menuItem->menu_title .= '!' ?>
                <?php endif ?>

                <?php if( !$existerelacion) : ?>
                <?php $menuItem->menu_title .= '?' ?>
                <?php endif ?>


                <?= $menuItem->menu_title ?>
            </span>

        </a>

    </li>

    <?php endif ?>

    <?php endforeach ?>
</ul>
<!-- /child menu -->