<!-- {% assign actives = page.active | split: "." %} -->
<!-- child menu -->
<ul class="menu">

    <?php foreach ($childs as $index =>$menuItem) : ?>

    <?php $hijos =$menuItem->buscarPorIdPadre( $menuItem->id ) ?>
    <?php $external_link = str_replace('.php', '', $menuItem->external_link) ?>
    <?php $existerelacion = mymenugenerador::esModeloOControlador($external_link) ?>

    <?php if( $hijos ) : ?>

    <?php View::partial('snippets/aside/level-menu', false, array('menupadre' => $menuItem)) ?>

    <?php else : ?>

    <li class="menu-item">

    <?php
    $link_name =  explode('/', $external_link);
    $max_size = count($link_name);
    $link = $external_link;
    if( is_file( APP_PATH."/controllers"."/". strtolower( $link_name[ $max_size - 1] ) .'_controller.php' ) ){
        $link = '/'.NOMBRE_CAJA.'/default/public/'. strtolower( $link_name[ $max_size - 1] );
        $existerelacion = true;

    }
    else
        {
            $link =  '/'.NOMBRE_CAJA.'/default/public/index/' . $link_name[ $max_size - 1] .'.php';
                    $existerelacion = true;

        }
    


    ?>

        <a href="<?php echo $link ?>" class="menu-link">

            <span class="menu-text">

                <?php if( !$external_link) : ?>
                <?php $menuItem->menu_title .= '!' ?>
                <?php endif ?>

                <?php if( !$existerelacion) : ?>
                <?php $menuItem->menu_title .= '?' ?>
                <?php endif ?>


                <?= $menuItem->menu_title ?>
            </span>

        </a>

    </li>

    <?php endif ?>

    <?php endforeach ?>
</ul>
<!-- /child menu -->
