<div class="modal fade" id="idSelecter" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableLabel"
    aria-hidden="true">

    <div class="modal-dialog modal-dialog-scrollable" role="document">

        <div class="modal-content">

            <div class="modal-header">
                <h5 id="exampleModalScrollableLabel" class="modal-title"> Selector </h5>
            </div>
            <div class="modal-body">

                <form>


                <div class="form-group">
        <label class="control-label" for="bss3">Live search</label>
        <select id="bss3" data-toggle="selectpicker" data-live-search="true" data-width="100%">
          <option>Hot Dog, Fries and a Soda</option>
          <option>Burger, Shake and a Smile</option>
          <option>Sugar, Spice and all things nice</option>
        </select>
      </div>

                </form>




                <div class="modal-footer">
                    <button data-dismiss="modal" type="button" class="btn btn-danger">Cerrar</button>
                </div>

            </div>
        </div>
    </div>
</div>