<div class="modal fade" id="idSelecter" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableLabel"
    aria-hidden="true">

    <div class="modal-dialog modal-dialog-scrollable" role="document">

        <div class="modal-content">

            <div class="modal-header">
                <h5 id="exampleModalScrollableLabel" class="modal-title"> Selector  </h5>
            </div>
            <div class="modal-body">

                <form>

                <div class="form-group">
                        <label class="control-label" for="select2-data-remote">Campo</label>
                        <select onchange="seleccionarField()" id="remotefield" class="form-control"></select>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="select2-data-remote">Datos</label>
                        <select onchange="seleccionarInfo()" id="remoteinfo" class="form-control"></select>
                    </div>

                </form>




                <div class="modal-footer">
                    <button data-dismiss="modal" type="button" class="btn btn-danger">Cerrar</button>
                </div>

            </div>
        </div>
    </div>
</div>


